export const Strings = {
  CoursesDetialsButton: 'تفاصيل الكورس',
  ConactUsTitle: 'تواصل معنا',
  CoursesTitle: 'الدورات',
  DictionaryTitle: 'القواميس',
  GreetingTextHomePage: 'مرحبا بك في تطبيق اشاراتي',
  TopicsTitleHomePage: 'أخر المواضيع',
  MyAcountGreetingText: 'مرحبا بك',
  MyAcountLogInText: 'تسجيل دخول / تسجيل',
  MyAcountContactUs: 'تواصل معنا',
  MyAcountAboutApp: 'عن التطبيق',
  MyAcountShareApp: 'شارك التطبيق',
  MyAcountScreenTitle: 'حسابي',
  MyAcountPersonMail: 'mohamed@gmail.com',
  MyAcountPersonName: 'محمد أحمد حسام الدين',
  MyAcountUpdateButton: 'تعديل الحساب',
  MyAcountCoursButton: 'الدورات',
  LogOut: 'تسجل الخروج',
  UpdateAccountTitle: 'إعدادات الحساب',
  LogInTitle: 'تسجيل الدخول',
  RestorPassButton: 'إستعادة كلمة المرور',
  DontHaveAccount: 'ليس لديك حساب ؟',
  RegisterNow: 'سجل الاَن',
  HaveAccount: 'لديك حساب ؟',
  LoginNow: 'سجل دخول الان',
};

export const placeholder = {
  ConactUsName: 'الأسم',
  ConactUsMail: 'البريد الإلكتروني',
  ContactUsMessage: 'هنا نص الرسالة',
  ContactUsSendButton: 'ارســال',
  UpdateAccountButton: 'حفظ',
  UpdateAccountPass: "كلمة السر",
  LogInButton: 'تسجيل دخول',
  RegisterButton: 'التسجيل',
};
