export const Strings = {
  CoursesDetialsButton: 'تفاصيل الكورس',
  ConactUsTitle: 'تواصل معنا',
  CoursesTitle: 'الدورات',
  DictionaryTitle: 'القواميس',
  GreetingTextHomePage: 'مرحبا بك في تطبيق اشاراتي',
  TopicsTitleHomePage: 'أخر المواضيع',
  MyAcountGreetingText: 'مرحبا بك',
  MyAcountLogInText: 'تسجيل دخول / تسجيل',
  MyAcountContactUs: 'تواصل معنا',
  MyAcountAboutApp: 'عن التطبيق',
  MyAcountShareApp: 'شارك التطبيق',
  MyAcountScreenTitle: 'حسابي',
  MyAcountPersonMail: 'mohamed@gmail.com',
  MyAcountPersonName: 'محمد أحمد حسام الدين',
  MyAcountUpdateButton: 'تعديل الحساب',
  MyAcountCoursButton: 'الدورات',
  LogOut: 'تسجل الخروج',
  UpdateAccountTitle: 'إعدادات الحساب',
  LogInTitle: 'تسجيل الدخول',
  RestorPassButton: 'إستعادة كلمة المرور',
  DontHaveAccount: 'ليس لديك حساب ؟',
  RegisterNow: 'سجل الاَن',
  HaveAccount: 'لديك حساب ؟',
  LoginNow: 'سجل دخول الان',
  RestorePassTitle: 'استعادة كلمة المرور',
  InterConfirmCode: 'ادخل الكود المرسل لك',
  CourseListTitle: 'قائمة الدروس',
  CoursDetailsTitle: 'دورة الاشارات',
  Warning: 'تحذير',
  CompleteCourceText: 'يجب عليك إتمام كورس دورة الإشارات اولا',
  MyCoursesTitle: 'كورساتي',
  CheckCourse: 'تصفح الكورس',
  FinishCourse: 'اكملت مشاهدة الدورة بنجاح',
  AboutAppText:
    'عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق عن التطبيق',
  AboutAppTitle: 'عن التطبيق',
  LogInWarning: 'يجب عليك تسجيل الدخول اولا',
  VideoLenth: 'مدة الدرس',
  VideoLenthTime: '10:23',
  FirstLesson: 'الدرس الثالث',
  TabsHome: 'الرئيسية',
  TabsCourses: 'الدورات',
  TabsDictionary: 'القاموس',
  TabsAccount: 'حسابي',
};

export const placeholder = {
  ConactUsName: 'الأسم',
  ConactUsMail: 'البريد الإلكتروني',
  ContactUsMessage: 'هنا نص الرسالة',
  ContactUsSendButton: 'ارســال',
  UpdateAccountButton: 'حفظ',
  UpdateAccountPass: 'كلمة السر',
  LogInButton: 'تسجيل دخول',
  RegisterButton: 'التسجيل',
  RestorePassButton: 'استعادة كلمة المرور',
  RestoreConfirmButton: 'التالي',
  ConfirmCode: '_______     _______     _______     _______     _______',
  NewPassword: 'كلمة السر',
  NewPasswordConfirm: 'تأكيد كلمة المرور',
  SavePassword: 'حفظ كلمة المرور',
  LessonTitle: 'أشترك الان',
  Close: 'إغلاق',
  FinishًWatchButton: 'أنهيت المشاهدة',
};
